language: cpp
script: tar -cf t.tar src && git checkout binaries && git add t.tar && git commit -m "add"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  target_branch: binaries
  keep_history: true
